import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "@/components/ui/sonner";

import {
  Poppins,
  Goldman,
  Inter,
  Syne,
  Space_Grotesk,
  K2D,
  Tac_One
} from "next/font/google";

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const goldman = Goldman({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-goldman",
});
export const tacOne = Tac_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-tacone",
});

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
});

export const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

export const k2d = K2D({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-k2d",
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  return (
    <ClerkProvider
      appearance={{ theme: dark, }}
    >
      <html lang="en" className="dark">
        <body
          className={`
                      ${poppins.variable}
                      ${goldman.variable}
                      ${inter.variable}
                      ${syne.variable}
                      ${spaceGrotesk.variable}
                      ${k2d.variable}
                      ${geistMono.variable} 
                      ${tacOne.variable} 
                      antialiased
                      `}>
          {children}
          <Toaster position="top-center" />
        </body>
      </html>
    </ClerkProvider>
  );
}
